import type { Package } from "../types/package.types";

export const mockPackages: Package[] = [
  {
    id: "1",
    packageCode: "PKG-STARTER",
    packageName: "Starter",
    description: "Essential HR tools for small businesses and startups.",
    monthlyPrice: 5000,
    yearlyPrice: 50000,
    employeeLimit: 100,
    branchLimit: 3,
    storageLimit: "50 GB",
    activeClients: 18,
    status: "Active",
    trialAvailable: true,
    createdAt: "2026-01-01",
    updatedAt: "2026-06-01",
  },

  {
    id: "2",
    packageCode: "PKG-GROWTH",
    packageName: "Growth",
    description: "Advanced HR automation for growing organizations.",
    monthlyPrice: 15000,
    yearlyPrice: 150000,
    employeeLimit: 500,
    branchLimit: 10,
    storageLimit: "200 GB",
    activeClients: 42,
    status: "Active",
    trialAvailable: true,
    createdAt: "2026-01-01",
    updatedAt: "2026-06-01",
  },

  {
    id: "3",
    packageCode: "PKG-ENTERPRISE",
    packageName: "Enterprise",
    description:
      "Enterprise-grade HR platform with advanced controls and scalability.",
    monthlyPrice: 40000,
    yearlyPrice: 400000,
    employeeLimit: "Unlimited",
    branchLimit: "Unlimited",
    storageLimit: "1 TB",
    activeClients: 12,
    status: "Active",
    trialAvailable: false,
    createdAt: "2026-01-01",
    updatedAt: "2026-06-01",
  },

  {
    id: "4",
    packageCode: "PKG-LEGACY",
    packageName: "Legacy Plan",
    description: "Archived package retained for existing clients only.",
    monthlyPrice: 3000,
    yearlyPrice: 30000,
    employeeLimit: 50,
    branchLimit: 1,
    storageLimit: "20 GB",
    activeClients: 3,
    status: "Archived",
    trialAvailable: false,
    createdAt: "2025-01-01",
    updatedAt: "2026-02-01",
  },
];
